# Generated by Django 4.1.5 on 2023-02-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=11)),
                ('date_subscribed', models.DateTimeField(auto_now=True)),
                ('messages_received', models.IntegerField()),
            ],
        ),
    ]
