# Generated by Django 4.1.7 on 2023-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(max_length=3),
        ),
    ]
