# Generated by Django 4.1.7 on 2023-03-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_delete_person_alter_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(),
        ),
    ]
